   # supabase/config.toml
   [api]
   enabled = true
   port = 54321
   schemas = ["public", "storage", "graphql_public"]
   
   [db]
   port = 54325
   
   [studio]
   enabled = true
   port = 54323
   
   [inbucket]
   enabled = true
   port = 54324